# Generated by Django 3.1.5 on 2021-01-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='app/images/')),
                ('github', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=250)),
            ],
        ),
    ]
